// Builds the web app's system prompt from the Claude Skill in .claude/skills/next-move.
// The Skill is the single source of truth: SKILL.md + references/*.md are concatenated
// into src/lib/method.generated.ts at build time. Runs automatically via "prebuild".
import { readFileSync, readdirSync, writeFileSync, mkdirSync } from "node:fs";
import { join, dirname } from "node:path";
import { fileURLToPath } from "node:url";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const skillDir = join(root, ".claude", "skills", "next-move");

const skillMd = readFileSync(join(skillDir, "SKILL.md"), "utf8");
// Strip YAML frontmatter — the description is for triggering in Claude Code, not for the prompt.
const body = skillMd.replace(/^---[\s\S]*?---\s*/, "");

const refDir = join(skillDir, "references");
const refs = readdirSync(refDir)
  .filter((f) => f.endsWith(".md"))
  .sort()
  .map((f) => `\n\n<!-- references/${f} -->\n\n${readFileSync(join(refDir, f), "utf8")}`)
  .join("");

const webRules = `

# Running inside the Next Move web app

You are answering through a web form, not a conversation. The person cannot reply to questions, so never ask any — make the most reasonable assumptions, produce the full output, and list the assumptions in one short line at the end of "The read".

Use exactly these three level-2 headings, in this order, and nothing before the first one:

## The read
## The artifact
## The next move

The artifact section must be self-contained markdown that reads correctly when copied on its own (start it with the artifact's own level-1 title). Do not wrap the artifact in a code fence.

The reference templates are included below. Read the one for the artifact you chose and follow its structure.`;

const out = `// GENERATED by scripts/build-prompt.mjs from .claude/skills/next-move — do not edit.
export const METHOD_PROMPT = ${JSON.stringify(body + webRules + refs)};
`;

mkdirSync(join(root, "src", "lib"), { recursive: true });
writeFileSync(join(root, "src", "lib", "method.generated.ts"), out);
console.log(`method.generated.ts: ${(body.length + webRules.length + refs.length).toLocaleString()} chars from SKILL.md + ${readdirSync(refDir).length} references`);
